twig:
    default_path: '%kernel.project_dir%/src/Infrastructure/Symfony/Frontend/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        taska: '@App\Infrastructure\Symfony\Twig\GlobalVariableService'
    
when@test:
    twig:
        strict_variables: true
