App\Domain\Core\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: App\Infrastructure\Doctrine\Repository\CommentRepository
    id:
        id:
            type: string
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: guid
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
        date:
            type: datetime
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
        comment:
            type: text
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
    manyToOne:
        task:
            targetEntity: App\Domain\Core\Entity\Task
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: comments
            joinColumns:
                task_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: App\Domain\Core\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: comments
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
